"""empty message

Revision ID: 079756033cbb
Revises: e615df44d500
Create Date: 2018-05-30 17:50:14.990913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079756033cbb'
down_revision = 'e615df44d500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
