"""empty message

Revision ID: cbf35a3fd437
Revises: 079756033cbb
Create Date: 2018-05-31 12:42:30.346273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf35a3fd437'
down_revision = '079756033cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'user_id')
    # ### end Alembic commands ###
